# Generated by Django 4.0.6 on 2022-07-13 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goldprice', '0002_goldpricepredictions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goldpricepredictions',
            name='high',
        ),
        migrations.RemoveField(
            model_name='goldpricepredictions',
            name='low',
        ),
        migrations.RemoveField(
            model_name='goldpricepredictions',
            name='open',
        ),
        migrations.RemoveField(
            model_name='goldpricepredictions',
            name='volume',
        ),
    ]
