# Generated by Django 4.0.6 on 2022-07-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldprice', '0003_remove_goldpricepredictions_high_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goldprice',
            name='growth',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='goldpricepredictions',
            name='growth',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
            preserve_default=False,
        ),
    ]
