# Generated by Django 4.0.6 on 2022-07-13 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goldpredictionlogic', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoldPricePredictions',
        ),
    ]
